
name: Healthcheck

# on:
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check that toskaboiler is alive
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: https://fs-toskaboiler.herokuapp.com/
          max-attempts: 3
          retry-delay: 10s